### ISSUE TITLE
模型 f1 值 总是为 0

### ISSUE THREAD

**Issue by km1994** [zhoujx4/NLP-Series-relation-extraction#2]
大佬的代码太赞了，但是不知道为什么，我训练的模型 的 f1 始终为 0

[Training] 251/251 [==============================] 551.6ms/step  loss: 3.0821 - subject_loss: 0.2884 - po_loss: 0.1985 08/23/2021 01:38:10 - INFO - root -   ***** Running Evalation *****
[Evaluating] 251/251 [==============================] 100.6ms/step08/23/2021 01:38:35 - INFO - root -   ============================================
08/23/2021 01:38:35 - INFO - root -   dev/entity_em: 0,
entity_pred_num&entity_gold_num: 0	1310 
08/23/2021 01:38:35 - INFO - root -   dev/entity_f1: 0.0, 
entity_precision: 0.0,
entity_recall: 0.0 
08/23/2021 01:38:35 - INFO - root -   ============================================
08/23/2021 01:38:35 - INFO - root -   dev/em: 0,
pre&gold: 0	1776 
08/23/2021 01:38:35 - INFO - root -   dev/f1: 0, 
Precision: 0,
Recall: 0.0 
08/23/2021 01:38:35 - INFO - root -   The F1-score is 0
08/23/2021 01:38:35 - INFO - root -   the best eval f1 is 0.0000, saving model !!
08/23/2021 01:38:41 - INFO - root -   ***** Running train *****
********************************************************************************

**Comment by zhoujx4** [comment]
也是跑run_mhs.py出现问题？ 有其他人反映过这个问题 ，
第一：跟我用的预训练模型是否一致？我用的是3层的roberta，
第二：要训练多几个epoch，只要loss是一直下降的，就可以继续训练下去，假如训练了5、6轮f1还是0，那再说吧。。。。

**Comment by km1994** [comment]
我模型也是使用 roberta，然后我跑了所有模型都是这样。

**Comment by zhoujx4** [comment]
四个模型都这样？ loss有没有下降？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月24日(周二) 上午8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhoujx4/NLP-Series-relation-extraction] 模型 f1 值 总是为 0 (#2)




 
我模型也是使用 roberta，然后我跑了所有模型都是这样。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by km1994** [comment]
找到原因
